version: '3.8'

services:
  app:
    build: .
    container_name: nestjs_app
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://admin:pass@mongo/dev_tahdir_db?authSource=admin&retryWrites=true&w=majority
    depends_on:
      - mongo
      - mongo-express

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
    ports:
      - '8081:8081'
    depends_on:
      - mongo

volumes:
  mongo_data:
